config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'customers', to: 'customers#index'
  get 'customers/alphabetized', to: 'customers#alphabetized', as: 'alphabetized_customers'
  get 'customers/missing_email', to: 'customers#missing_email', as: 'missing_email_customers'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/customer.rb
class Customer < ApplicationRecord
    validates :full_name, presence: true
    has_one_attached :image
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController
    def index
        @customers = Customer.all
    end

    def alphabetized
        @alph_customers = Customer.order(full_name: :asc)
    end

    def missing_email
        @missing_email_customers = Customer.where(email_address: '')
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/views/customers/_customer.html.erb
<div class="column">
  <div class="card">
    <div class="card-content">
      <p class="title">
          <%= customer.full_name %>
      </p>
      <% if customer.image.present? %>
        <div class="card-image">
          <figure class="image">
            <%= image_tag customer.image.variant(resize_to_limit:[500,500]) %>
          </figure>
        </div>
      <% end %>
    </div>
    <footer class="card-footer">
      <p class="card-footer-item">
        Phone Number: <br><%= customer.phone_number %>
      </p>
      <p class="card-footer-item">
        Email Address: <br><%= customer.email_address %>
      </p>
      <p class="card-footer-item">
        Notes: <br><%= customer.notes %>
      </p>
    </footer>
  </div>
</div>

app/views/customers/alphabetized.html.erb
<h3 class="title is-4">Alphabetized Customers</h3>

<div class="columns is-multiline">
  <%= render partial: 'customer',
            collection: @alph_customers,
            locals: { show_link: true } %>
</div>

<%= link_to "All Customers", customers_path %>
<%= link_to "Customers without Email", missing_email_customers_path %>

app/views/customers/index.html.erb
<h3 class="title is-4">Customers</h3>

<div class="columns is-multiline">
  <%= render partial: 'customer',
            collection: @customers,
            locals: { show_link: true } %>
</div>

<%= link_to "Alphabetized Customers", alphabetized_customers_path %>
<%= link_to "Customers without Email", missing_email_customers_path %>

app/views/customers/missing_email.html.erb
<h3 class="title is-4">Customers with Missing Email</h3>

<%= @missing_email_customers.length %>

<div class="columns is-multiline">
  <%= render partial: 'customer',
            collection: @missing_email_customers,
            locals: { show_link: true } %>
</div>

<%= link_to "All Customers", customers_path %>
<%= link_to "Alphabetized Customers", alphabetized_customers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>U6Crm</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>